### ISSUE TITLE
Feature: Transfer Past and Upcoming Events Recycler view into Compose UI

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#1]
### Feature description

You have to transfer Past Events and Upcoming Events Recycler view into Compose UI

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
i want to work on this issue please assign me

**Comment by MohitGupta121** [comment]
Done @ismailbohra  Go ahead.

**Comment by MohitGupta121** [comment]
Thanks @ismailbohra
