### ISSUE TITLE
Feature: Implement Event Details Fragment with Firebase using Compose

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#13]
### Feature description

Implement Event Details Fragment with Firebase like below using Compose:- 

https://user-images.githubusercontent.com/76530270/194017774-79a93a62-4277-471f-a7b4-c035a356ec85.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
please assign me this task

**Comment by MohitGupta121** [comment]
@ismailbohra assigned go ahead.
