### ISSUE TITLE
Feature: Implement Team Fragment using Compose

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#14]
### Feature description

Feature: Implement **Team Fragment** using Compose like below demo:-

https://user-images.githubusercontent.com/76530270/194018743-3454ff1f-e966-480e-b9ab-c02ca8ee0771.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Kardelio** [comment]
Hey @MohitGupta121 this looks like a really cool project and a nice task to get involved with, would you mind if I pick up this task and tackle it? Is that ok?

**Comment by MohitGupta121** [comment]
@Kardelio Yes sure.

**Comment by Kardelio** [comment]
@MohitGupta121 awesome thank you I'll get straight on it! Thanks for assigning!

**Comment by MohitGupta121** [comment]
@Kardelio Ah no problem😅, Use this dummy data and images to implement this screen.

**Comment by Kardelio** [comment]
Just to be clear @MohitGupta121 this is a brand new screen in the app right?

**Comment by MohitGupta121** [comment]
Yes @Kardelio you have to create new screen using compose for team.

**Comment by Kardelio** [comment]
Perfect ok :) thanks! on it

**Comment by Kardelio** [comment]
@MohitGupta121 I dont see the image at the top of this design in the codebase anywhere...
Is there somewhere I can access this image?
<img width="196" alt="Screenshot 2022-10-06 at 12 48 43" src="https://user-images.githubusercontent.com/10523656/194294516-7f62d886-cd85-4b07-9acb-5b6e93820f6e.png">

**Comment by Kardelio** [comment]
> @Kardelio Ah no problem😅, Use this dummy data and images to implement this screen.

You mean I should create dummy data based on the design in the video in the Issue? As in the dummy data does not exist yet?

**Comment by MohitGupta121** [comment]
> > @Kardelio Ah no problem😅, Use this dummy data and images to implement this screen.
> 
> You mean I should create dummy data based on the design in the video in the Issue? As in the dummy data does not exist yet?

Add data file yourself, images and all other stuff.
Or add only 1 person data and duplicate it for every person.

**Comment by Kardelio** [comment]
> 

Okie dokie :)

**Comment by MohitGupta121** [comment]
> @MohitGupta121 I dont see the image at the top of this design in the codebase anywhere... Is there somewhere I can access this image? <img alt="Screenshot 2022-10-06 at 12 48 43" width="196" src="https://user-images.githubusercontent.com/10523656/194294516-7f62d886-cd85-4b07-9acb-5b6e93820f6e.png">

https://www.processmaker.com/wp-content/uploads/2021/05/Process-efficiency-768x535.jpg

Take the image from there @Kardelio

**Comment by Kardelio** [comment]
thank you

**Comment by Harsh-raj-x07** [comment]
hey @MohitGupta121 mohit it would be a great opportunity for me If I could resolve this issue I have already worked on this problem once ?

**Comment by MohitGupta121** [comment]
@Harsh0326 pick other issue @Kardelio is working on this.

**Comment by MohitGupta121** [comment]
@Kardelio are you working on this?

**Comment by Harsh-raj-x07** [comment]
P> @Harsh0326 pick other issue …..ooo

**Comment by Kardelio** [comment]
@MohitGupta121 yes I'm working on this :)

**Comment by MohitGupta121** [comment]
@Kardelio okay great.

**Comment by Kardelio** [comment]
FYI @MohitGupta121 i have created a PR (https://github.com/MohitGupta121/gdsc-android-ipsa/pull/26/) for this issue, thanks

**Comment by MohitGupta121** [comment]
@Kardelio okay thanks I'll review it.
