### ISSUE TITLE
Feature: Implement Back Button at Top Bar

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#20]
### Feature description

Feature: Implement Back Button at Top Bar 

- Certificate Verify Screen
- Event Details Screen

| | |
|:----------------------------------------:|:-----------------------------------------:|
| ![](https://user-images.githubusercontent.com/76530270/194563935-f3f8a235-b3c3-44c1-806c-d635769a73c7.png) | ![Screenshot_2022-05-31-12-23-27-332_com android camera](https://user-images.githubusercontent.com/76530270/194563964-ffc5c296-c4be-42f2-9b5b-eb8e992535d6.png) |
|||

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
i want to work on this

**Comment by MohitGupta121** [comment]
@ismailbohra assigned, go ahead.
