### ISSUE TITLE
Change Bottom Bar Selected Color 

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#21]
Change Bottom Bar selected item color to Purple `#800080`

![image](https://user-images.githubusercontent.com/76530270/194565028-e2e3be4d-90b1-4808-aa97-6d3fe3a0454d.png)

**Comment by Harsh-raj-x07** [comment]
hey @MohitGupta121 it would be a great opportunity for me If I could resolve this issue I have already worked on this problem once

**Comment by MohitGupta121** [comment]
@Harsh0326 yes sure, go ahead.

**Comment by Vivek-raj-gupta-2002** [comment]
@MohitGupta121 I wanted it to try may I??
