### ISSUE TITLE
Feature: Implement Placeholder if there is no Upcoming Events.

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#28]
### Feature description

Implement Placeholder if there is no Upcoming Events.

you have to add the animation if there is no events get from firebase for upcoming events:-

Animation:- https://gist.github.com/MohitGupta121/0a76e9abc940d688695e6fbf6eb29880#file-searching_lottie-json

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
please assign me this task
