### ISSUE TITLE
Feature: Implement Bottom Navigation with Toolbar using Compose

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#3]
### Feature description

Implement Bottom Navigation with Toolbar using Jetpack Compose UI

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
please assign me this task

**Comment by MohitGupta121** [comment]
Done @ismailbohra Go ahead.
