### ISSUE TITLE
Feature: Implement Certificate Verification Fragment

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#8]
### Feature description

Implement Certificate Verification Fragment:-
| Home Screen | Verify Screen |
|:----------------------------------------:|:-----------------------------------------:|
| ![](https://user-images.githubusercontent.com/76530270/193743727-5e0862cb-223b-48dc-b2e6-c5be5b4460aa.png) | ![Screenshot_2022-05-31-12-23-27-332_com android camera](https://user-images.githubusercontent.com/76530270/193743763-b0458cf6-3610-471c-a4ef-9bc738883a1c.png) |
|||

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
I want to work on this task please assign me

**Comment by MohitGupta121** [comment]
@ismailbohra first work on about us then move to this I think

**Comment by Moizcode** [comment]
I want to work on this task, please assign me

**Comment by MohitGupta121** [comment]
@Moizcode go ahead, but use MVVM pattern

**Comment by Moizcode** [comment]
@MohitGupta121 okay
