### ISSUE TITLE
Feature: Implement About Us Fragment with Gif & using Card Views

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/gdsc-android-ipsa#9]
### Feature description

Implement About Us Fragment with Gif & using Card Views **no need to use Recyclerview for Different Tracks**:-

- Make UI like this mockup recording

https://user-images.githubusercontent.com/76530270/193744629-816fe30b-ea2a-43cb-9001-d9a5cf849ea6.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ismailbohra** [comment]
please assign me this task

**Comment by MohitGupta121** [comment]
@ismailbohra assigned go ahead
